### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by monsterkitten** [nodejs/inclusivity#34] opened 2015-11-18 01:14 UTC
This issue follows the Node COC, and thus, according to @juliepagano, should remain.

Could someone please explain to me why it is an important use of time and effort to obsess over and change the names of things in the code of a javascript runtime, rather than actually improving its functionality?

**Comment by ilovecocks1234** [comment] 2015-11-18 01:29
>Could someone please explain to me why it is an important use of time and effort to obsess over and change the names of things in the code of a javascript runtime, rather than actually improving its functionality?

Women make up something like 51% of the world's population.

They make up less than FIVE PERCENT of FOSS contributors.

Can you imagine how much better Node might be if it had nearly twice as many contributors? Twice as many eyes looking intently over each changeset? Twice as many fingers typing code on twice as many laptops? Twice as many people working to build the new web?

I can tell you what it would be. It would be node's full potential realised.

**Comment by monsterkitten** [comment] 2015-11-18 01:39
Are you implying that more women would contribute to FOSS if, for example, in the code, instead of saying "he" to describe the user , they used "(s)he"?

Also, could you please source both of your claims?

Lastly, I believe you are simply ignoring the postulate that not nearly as many females as males show an interest in the computing field, much less in contributing to FOSS.

**Comment by ilovecocks1234** [comment] 2015-11-18 01:45
>Are you implying that more women would contribute to FOSS if, for example, in the code, instead of saying "he" to describe the user , they used "(s)he"?

'(s)he' is pretty awful. It's a step below 'they', which is a step below 'rewriting in the passive voice'. 
Still, not making assumptions about gender is likely to have a positive impact on the view of non-men of node. See Sue, 2010, 'Microaggressions in Everyday Life: Race, Gender, and Sexual Orientation'.

The claim that 51% of the world's population is women needs no source. It's simply common sense. I don't think you really believe that it's a controversial topic.

On non-men in FOSS: Please refer to Ghosh et al, 2005. They found a participation rate of two percent.

>Lastly, I believe you are simply ignoring the postulate that not nearly as many females as males show an interest in the computing field, much less in contributing to FOSS.

I'm not. Why do you think that's the case? Magic compsci balls that naturally gravitate towards men?
It'd require an in-depth explanation of the effects of the patriarchy to explain this totally. But I want you to consider the way things move from birth, from when women get barbies and boys get lego, from when women are encouraged into the 'caring professions' and men into the 'constructive', of the unpaid labour women must offer in reproductive labour, and, yes, in the discouragement of women from participation in FOSS through microaggressions in source code, machissmo behaviour (hello Linus Torvalds), and people who believe women's concerns don't matter because it's "not an important use of time and effort."

**Comment by Wysaard** [comment] 2015-11-18 01:59
@ilovecocks1234

Isn't your view just the bigotry of low expectations? (Women can't handle code if it contains microagressions or masculine forms are used too often, while men clearly don't care about either)

If anything, your comment in kinda sexist, in that you're suggesting these are "women's concerns", as if women in general obsess over stuff like this

**Comment by monsterkitten** [comment] 2015-11-18 02:02
>'(s)he' is pretty awful. It's a step below 'they', which is a step below 'rewriting in the passive voice'. 
That seems pretty arbitrary.
>Still, not making assumptions about gender is likely to have a positive impact on the view of non-men of node.
By saying "he" in this context, an assumption about gender is [bold]not[/bold] being made. It is simply used as a placeholder since the English language does not have a gender-neutral personal pronoun. It does not 

>I'm not. Why do you think that's the case? Magic compsci balls that naturally gravitate towards men?
>It'd require an in-depth explanation of the effects of the patriarchy to explain this totally. But I want you to consider the way things move from birth, from when women get barbies and boys get lego, from when women are encouraged into the 'caring professions' and men into the 'constructive', of the unpaid labour women must offer in reproductive labour, and, yes, in the discouragement of women from participation in FOSS through microaggressions in source code, machissmo behaviour (hello Linus Torvalds), and people who believe women's concerns don't matter because it's "not an important use of time and effort."
You are pretty much strawmanning me. I understand how society and gender work. I am think that is the case because you said "almost double" the amount of contributors, which just would not happen.

**Comment by jden** [comment] 2015-11-18 02:05
> Could someone please explain to me why it is an important use of time and effort

I'll quote [node's code of conduct](https://github.com/nodejs/node/blob/master/CODE_OF_CONDUCT.md):

> We are committed to providing a friendly, safe and welcoming environment for all, regardless of gender, sexual orientation, disability, ethnicity, religion, or similar personal characteristic.

Further, use of emotionally charged language is rarely appropriate in software, as it tends to distract from rather than contribute to clear expression of intent and effort developing and understanding the system itself.

**Comment by ilhamiavnery** [comment] 2015-11-18 02:06
@Wysaard 
No. It affects men as well. The schizophrenic man would be put off by a comment that derides 'psychotic' or 'crazy' people. The gay man will be upset by assumptions of girlfriends. The man of colour by racist or encumbered terminology. I could go on, really.

It even affects straight men. If I were to post about 'middle-class white cishet male tears' I would be jumped on by those who felt deeply affected by what would be an offhand comment. 

>By saying "he" in this context, an assumption about gender is NOT being made. It is simply used as a placeholder since the English language does not have a gender-neutral personal pronoun

It's an awful placeholder, and one that could be replaced by 'they' (not that I like singular-'they', but it's better than 'he'.) 
Don't write sentences in documentation that require that level of intimacy where you don't need to. Even asiding the gender problems, it has a creepy flow to it, it disrupts the demeter of the text.

>You are pretty much strawmanning me. I understand how society and gender work. I am think that is the case because you said "almost double" the amount of contributors, which just would not happen.

It might happen; you don't know for sure. I don't think that simply replacing problematic sentences alone would, but we must patch the small cracks if we are to get this ship back on the seas.

**Comment by Wysaard** [comment] 2015-11-18 02:14
Isn't it the case that pretty much anything can trigger some person somewhere on the globe? How about only changing language for clarity's sake and style, instead of caring about not offending anyone which is pretty much impossible anyway.

This entire discussion about appropriate words is completely useless as far as I'm concerned, and the only reason I participate is in the hope that this will be over sooner. 

If you really think any problems in the community are solved this way (by moderating language for fear of offense, microagressions etc.) I think you are in for an unpleasant surprise.

**Comment by monsterkitten** [comment] 2015-11-18 02:18
@jden
Okay.

@ilhamiavnery 
What happened to ilovecocks1234?

Anyways. 

> The gay man will be upset by assumptions of girlfriends

I am a gay man. I don't let that upset me. That is the stupidest thing I have ever heard. I understand that someone would say that because they are a straight person. I don't just get upset because someone assumes I'd have a girlfriend, I would either say "Actually, I'm gay," or nothing at all because i understand the point that was being made. 

>It's an awful placeholder, and one that could be replaced by 'they' (not that I like singular-'they', but it's better than 'he'.) 

Again, arbitrary. 

>Don't write sentences in documentation that require that level of intimacy where you don't need to. Even asiding the gender problems, it has a creepy flow to it, it disrupts the demeter of the text

That is just false. If a person lets the word "he" get him or her off track while reading, that is a problem with their reading skills.

>It might happen; you don't know for sure. 

You're ignoring the part about your strawman tangent. 
Sure, anything might happen. But that doesn't mean I make assertions that please me just because they *could* happen.

>I don't think that simply replacing problematic sentences alone would, but we must patch the small cracks if we are to get this ship back on the seas.

That is not really a good simile for this, but I won't waste time on it.

**Comment by jden** [comment] 2015-11-18 02:18
@Wysaard this is a false dichotomy. https://github.com/nodejs/node/pull/3743 improved clarity *and* reduced usage of awkward and painful language.

**Comment by ilhamiavnery** [comment] 2015-11-18 02:39
>I don't let that upset me

It's not about you. It's about a whole diverse population. It doesn't hurt to remove assumptions like these. 
With all respect, how families are constructed and gender politics don't belong in software. We are the ones who are trying to take that kind of thing out of software; we don't want programs to go around telling their users what they are and how their family should be structured.

.>Again, arbitrary.

But backed by lots of anecdotes. I don't think a study on whether singular they as compared to he works better will ever be commissioned, but I am almost certain that 'he' - which is totally unnatural for a user manual or documentation, which are supposed to stay away from imposing their structure and worldview on the user - would lose. 'They' is better, but *writing the documentation to read like documentation*, i.e., without any personal pronouns, is better.

>That is just false. If a person lets the word "he" get him or her off track while reading, that is a problem with their reading skills.

No, it's not. People vary. Some people are affected by these things. Since it isn't hard to replace it, and because keeping 'he' has zero - in fact, a negative - benefit factor, it's worthless to keep it when we can change it.
We are already talking about this, we have shown that we have more than enough time to do this.

>Sure, anything might happen. But that doesn't mean I make assertions that please me just because they could happen.

Again, refer to Microaggressions in Everyday Life for quantative evidence that dealing with these issues improves participation rates amongst minority and oppressed groups.

**Comment by monsterkitten** [comment] 2015-11-18 02:47
>It's not about you. It's about a whole diverse population. It doesn't hurt to remove assumptions like 
these.

Of course it's not about me. But it's about a group that includes me. If people are risen in this environment that babies them and grows their skin no thicker than paper, they are weak. People need to grow up, is what I am saying. I did.

>With all respect, how families are constructed and gender politics don't belong in software. We are the ones who are trying to take that kind of thing out of software; we don't want programs to go around telling their users what they are and how their family should be structured.

You are on some crazy type of tangent right now.

>But backed by lots of anecdotes. I don't think a study on whether singular they as compared to he works better will ever be commissioned, but I am almost certain that 'he' - which is totally unnatural for a user manual or documentation, which are supposed to stay away from imposing their structure and worldview on the user - would lose. 'They' is better, but writing the documentation to read like documentation, i.e., without any personal pronouns, is better.

Okay.

>No, it's not. People vary. Some people are affected by these things. Since it isn't hard to replace it, and because keeping 'he' has zero - in fact, a negative - benefit factor, it's worthless to keep it when we can change it.
We are already talking about this, we have shown that we have more than enough time to do this.

Okay.

>Again, refer to Microaggressions in Everyday Life for quantative evidence that dealing with these issues improves participation rates amongst minority and oppressed groups.

I would, but frankly I don't feel like spending money on it, and I feel like I would probably bore myself half to death reading it. I'm not saying that its contents are not important, but yeah.

**Comment by Wysaard** [comment] 2015-11-18 10:58
@jden
I'm not saying it can't be both. I'm just saying that only the clarity matters.

**Comment by 950c** [comment] 2015-11-18 11:10
>Could someone please explain to me why it is an important use of time and effort to obsess over and change the names of things in the code of a javascript runtime, rather than actually improving its functionality?

It isn't. These people have an agenda that has nothing to do with improving software.

**Comment by Wysaard** [comment] 2015-11-18 11:18
@950c
I wouldn't be too sure of that. A lot of people have started to buy into this idea of having to carefully choose your words, lest it be ableist, microaggressive, homophobic, sexist, racist, and so forth, even if what you are trying to say is none of those things.

I get the impression that this is becoming the norm in the US, as most Americans I speak to seem to agree with this. Were it not for the internet however, I wouldn't even know it existed. Were it not spreading so rapidly, I would be laughing it in the face. But here we are.

**Comment by Fishrock123** [comment] 2015-11-18 18:46
> Could someone please explain to me why it is an important use of time and effort to obsess over and change the names of things in the code of a javascript runtime, rather than actually improving its functionality?

The number of PRs and Issues on the repo between such things is on the order of hundreds. While there was a heated discussion about a name change a week ago, https://nodejs.org/en/blog/release/v5.1.0/ also represents the last 3 week's worth of work (well, some of it), so I think these concerns are very unwarranted.

**Comment by isaacs** [comment] 2015-11-18 20:15
The OP question was: "Should we spend time and energy being concerned about the language used in a software project?"

The answer is "Yes, we should, because a more inclusive community makes better software."

You can disagree with the premise in the answer, but it's already been accepted by the foundation and contributors that own and operate the Node.js project.  It's not controversial at this point.

I suggest closing (and even locking) this issue, since the OP's question has been adequately answered.  There is no point continuing to try to re-legislate this point

**Closed** 2015-11-19 15:48 UTC
