### ISSUE TITLE
Inclusivity to the non neurotypical

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/inclusivity#17] opened 2015-11-13 22:03 UTC
Briefly mentioned but burried in https://github.com/nodejs/inclusivity/issues/9#issuecomment-156556174

> The one thing I do think that we need to be cognizant of is that being inclusive of everyone does include being inclusive and understanding to those who are not neurotypical. Our industry and community is made up of many outstanding and brilliant individuals who's brains genuinely function differently, and do not see this problem the same way.

> We need to make sure that we treat those who are contributing with the respect they deserve, and make sure to not attack those that may just need some guidance or compassion when trying to navigate the landscape of node.

**Comment by jasnell** [comment] 2015-11-13 22:06
As the father of a child on the Autism spectrum, big +1 to this one.

**Comment by nebrius** [comment] 2015-11-13 22:41
Another big +1 to this. Especially in documentation, where this often shows up.

**Comment by malandrew** [comment] 2015-11-13 23:10
I would also add non-native English speakers and extending them the benefit of the doubt in choice of diction. 

I once used a word that has strong negative connotations in American English, but not in my first language Portuguese, and got crucified for it. I have native fluency in English, but haven't internalized the sensitivity of many words either because I'm on the aspie side of things or because many words have mixed semantics due to the two languages and cultures through which I experience the world.

Everyone loves to talk about the privileges that white heterosexual males have (before anyone asks anything, I'll volunteer that I'm mixed race, mixed nationality and identify as pomosexual), but we conveniently ignore the greatest privilege that anyone participating in these discussions in the NodeJS community have and that is a strong command of the the English language, without which you literally do not have a voice in the community. One top of easily making mistakes to which someone might take offense, a non-native speaker likely carries none of the emotional baggage that a native English speaker may have in relation to the use of specific words. I've on several occasions seen non-native speakers attacked because they were oblivious to cultural baggage associated with a word, or at least oblivious enough in real time to utter the word and only in hindsight realize the faux pas after being attacked.

The complete lack of benefit of the doubt (assumption of innocence before proving guilty) and the nurturing of a victimhood culture has made this community not only wholly unwelcoming but unsafe.

This blog post by a well known biohacker does a great job of capturing my concerns about the direction the NodeJS community has taken:
https://medium.com/@maradydd/when-nerds-collide-31895b01e68c

**Comment by juliepagano** [comment] 2015-11-13 23:28
I think these are excellent cases for having clear, helpful standards written out that can be referenced, so everyone has the ability to understand what is expected when participating. Standards gives folks a place to check where there may be differences that are non-obvious to them. Standards also provide a nice place to point people when they make a honest mistake that needs to be corrected (vs having a giant thread of people piling on). Someone making an honest mistake shouldn't be treated poorly and should be given a chance to adjust to the standards of the community.

**Comment by mikeal** [comment] 2015-11-13 23:30
non-native english speakers is already on the list of considerations.

**Comment by malandrew** [comment] 2015-11-14 00:04
@juliepagano "Someone making an honest mistake shouldn't be treated poorly and should be given a chance to adjust to the standards of the community."

I'm sorry, but that has not been my experience. The assumption that people are categorically wrong and need to be "corrected" as a default attitude is the direction of intolerance. People who are aspie/autistic and people who are non-native English speakers are not wrong/broken and don't need to be "corrected" to increasingly meet the "standards" of an increasingly **neurotypical** community and a community where more of the leadership are native English speakers of American upbringing (and are therefore likely blind to the importance of this tolerance)

Pretty much every prominent non-native American English speaking member of the NodeJS open source community rarely if ever participate in these discussions. So this perspective is largely unconsidered.

Lastly, do you not see the irony in placing emphasis on "having clear, helpful standards written out [in American English] that can be referenced, so everyone [with a strong command of American English] has the ability to understand what is expected when participating."

Personally, I prefer a culture of tolerance and acceptance of misunderstanding.

**Comment by mikeal** [comment] 2015-11-14 00:09
@malandrew actually, efforts are already under way to simplify the language in documentation, particularly the documentation regarding conduct, so that it is easier to understand with limit English skills and also so that it can be translated easily in to other languages without losing context. That is much more preferable than throwing up our hands and not defining conduct and language guidelines at all.

**Comment by sup** [comment] 2015-11-14 00:11
additionally, i18n is slowly starting to get active again, guidelines on translation are being written and so, support for non-native english speakers is going to get better anyways!

**Comment by juliepagano** [comment] 2015-11-14 00:17
@malandrew I never suggested that people are wrong/broken. Please do not put ableist words in my mouth. Communities often have standards of acceptable behavior and people are generally expected to follow them to the best of their ability (with room for exceptions, when needed). My understanding from some friends on the spectrum is that having rules for expected behavior can be helpful because it is not easy for then to intuit those things in a way that neurotypical people may be able to. Most of them are also sick of bad behavior in the tech industry being scapegoated on the non-neurotypical, but perhaps that is a tangent.

Any standards the WG develops should be in very simple english (e.g. leaving out less common words that a non-native english speaker would have difficulty with), so that it is approachable to non-native english speakers. The standards should be considerate of the diversity of the participants (including non-neurotypical, non-native english speakers, non-western people, etc.). I think the WG has shown a willingness to do this and is working on including several non-native english speakers to make sure their concerns are represented in discussions and decision-making.

**Comment by malandrew** [comment] 2015-11-14 00:28
@mikeal "That is much more preferable than throwing up our hands and not defining conduct and language guidelines at all."

That isn't what I'm suggesting at all. I'm suggesting that the direction should be towards talking about tolerance and how people already in the community can be more tolerant and how new members to the community should be expected to be tolerant. Right now, we're codifying intolerance. 

There is nothing in the current code of conduct regarding an expectation of tolerance and expectation of an assumption of benefit of the doubt or assumption of good faith.
https://github.com/nodejs/node/blob/master/CODE_OF_CONDUCT.md

The closest it gets is the line item that begins "Respect that people have differences of opinion...", but the rest of that one scopes that expectation down to matters related to design/technical discussion. 

The first item has a catch all for "similar personal characteristic", but it would be nice if neurological style, native tongue and cultural viewpoint are considered first class citizens in that list.

**Comment by malandrew** [comment] 2015-11-14 00:37
@juliepagano You've just done exactly what I feared. I didn't intend wrong/broken to come across as ableist.  That was not my intent at all with that statement. i was trying to place emphasis on the idea that an assumption of correctness of behavior as a goal is contrary to tolerance. Wrong and broken are acceptable synonyms to incorrect (the word I probably should have used in hindsight), which is the antonym of correct.

On that note, having now been misunderstood and accused of fostering ableist language, I'm out, because I've seen where this leads. If we had a community cultural norm of tolerance, you would have tried to seek further clarification of my intent instead of jumping to conclusions of what I was trying to say.

**Comment by juliepagano** [comment] 2015-11-14 00:43
Created #20 for discussion of the issues around supporting non-native english speakers since it is a different enough thing from supporting non-neurotypical people.

**Comment by 950c** [comment] 2015-11-16 19:05
As as person diagnosed with Asperger syndrome I don't see any reason to change anything. Are you trying to say that because of my condition I'm somehow a lesser being and others will have to make concessions for me? Please don't. That would make me feel uncomfortable.

**Comment by bungle** [comment] 2015-11-17 16:27
Are you writing a software or what? This continues here as well:
https://github.com/nodejs/node/issues/3721

Please, stop this immediately. Don't you understand that these are a words that are used in CONTEXT.

**Comment by nebrius** [comment] 2016-01-22 18:12
After some consideration, I'm going to close this issue. It's an important topic, and I hope to see more progress on this going forward, but I think this conversation has run it's course.

I hope to see more issues files on this topic though, both for new policies and new programs. We have new [guidelines for filing issues](https://github.com/nodejs/inclusivity/blob/master/docs/POLICY_ISSUES.md), so please be sure to take a look.

@TheAlphaNerd, if you would like to reopen this issue, can you rework the OP to match the new guidelines? Feel free to ping me or any other WG members if you have any questions/concerns!

**Closed by nebrius** 2016-01-22 18:12 UTC
Labels: question
